/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourceControlTransitions.java
 *
 * Created on 23-Apr-2012, 11:28:40 AM
 */
package webcamstudio.components;

import javax.swing.DefaultListModel;
import webcamstudio.channels.transitions.Transition;
import webcamstudio.streams.SourceChannel;
import webcamstudio.streams.Stream;

/**
 *
 * @author patrick
 */
public class SourceControlChannels extends javax.swing.JPanel {
    Stream source = null;
    /** Creates new form SourceControlTransitions */
    @SuppressWarnings("unchecked") 
    public SourceControlChannels(Stream source) {
        initComponents();
        this.source=source;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        setName(bundle.getString("CHANNELS_CTRL")); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Import Stream Settings to All Channels");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SourceChannel sch = null;
        for (int i=0; i < source.getChannels().size(); i++){
            String scName = source.getChannels().get(i).getName();
            sch=SourceChannel.getChannel(scName, source);
            source.removeChannelAt(i);
            source.addChannelAt(sch,i);
        }
        ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, "Stream Settings Applied to all Channels.");
        ResourceMonitor.getInstance().addMessage(label);
    }//GEN-LAST:event_jButton1ActionPerformed
    @SuppressWarnings("deprecation")     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
