/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HSBControl.java
 *
 * Created in 2013.
 */

package webcamstudio.sources.effects.controls;

import webcamstudio.sources.effects.Erode;

/**
 *
 * @author pballeux (modified by karl)
 */
public class ErodeControl extends javax.swing.JPanel {

    Erode effect = null;
    /** Creates new form MosaicControl
     * @param effect */
    public ErodeControl(Erode effect) {
        initComponents();
        this.effect=effect;
        sliderErode.setValue(effect.getErFactor());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderErode = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(396, 107));

        sliderErode.setMaximum(200);
        sliderErode.setMinorTickSpacing(20);
        sliderErode.setPaintLabels(true);
        sliderErode.setPaintTicks(true);
        sliderErode.setValue(0);
        sliderErode.setName("sliderErode"); // NOI18N
        sliderErode.setOpaque(true);
        sliderErode.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderErodeStateChanged(evt);
            }
        });

        jLabel1.setText("Erode Strength");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderErode, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderErode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sliderErodeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderErodeStateChanged
        int value = sliderErode.getValue();
        if (value != 0) {
            effect.setErFactor(value);
        }
    }//GEN-LAST:event_sliderErodeStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider sliderErode;
    // End of variables declaration//GEN-END:variables

}
