/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MosaicControl.java
 *
 * Created on 2010-01-15, 01:51:51
 */

package webcamstudio.sources.effects.controls;

import webcamstudio.sources.effects.Perspective;

/**
 *
 * @author pballeux
 */
public class PerspectiveControl extends javax.swing.JPanel {

    Perspective effect = null;
    /** Creates new form MosaicControl
     * @param effect */
    public PerspectiveControl(Perspective effect) {
        initComponents();
        this.effect=effect;
/*        txtX1.setText((int)effect.getX1()+"");
        txtY1.setText((int)effect.getY1()+"");
        txtX2.setText((int)effect.getX2()+"");
        txtY2.setText((int)effect.getY2()+"");
        txtX3.setText((int)effect.getX3()+"");
        txtY3.setText((int)effect.getY3()+"");
        txtX4.setText((int)effect.getX4()+"");
        txtY4.setText((int)effect.getY4()+""); */
        jSpinX1.setValue((int)effect.getX1());
        jSpinY1.setValue((int)effect.getY1());
        jSpinX2.setValue((int)effect.getX2());
        jSpinY2.setValue((int)effect.getY2());
        jSpinX3.setValue((int)effect.getX3());
        jSpinY3.setValue((int)effect.getY3());
        jSpinX4.setValue((int)effect.getX4());
        jSpinY4.setValue((int)effect.getY4());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSpinX1 = new javax.swing.JSpinner();
        jSpinY1 = new javax.swing.JSpinner();
        jSpinX2 = new javax.swing.JSpinner();
        jSpinY2 = new javax.swing.JSpinner();
        jSpinX3 = new javax.swing.JSpinner();
        jSpinY3 = new javax.swing.JSpinner();
        jSpinX4 = new javax.swing.JSpinner();
        jSpinY4 = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(414, 154));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        label.setText("X Top L ");
        label.setName("label"); // NOI18N
        add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("X Top R");
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("X Bottom R");
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("X Bottom L");
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Y Top L");
        jLabel4.setName("jLabel4"); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel5.setText("Y Top R");
        jLabel5.setName("jLabel5"); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel6.setText("Y Bottom R");
        jLabel6.setName("jLabel6"); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel7.setText("Y Bottom L");
        jLabel7.setName("jLabel7"); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jSpinX1.setName("jSpinX1"); // NOI18N
        jSpinX1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinX1StateChanged(evt);
            }
        });
        add(jSpinX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 64, -1));

        jSpinY1.setName("jSpinY1"); // NOI18N
        jSpinY1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinY1StateChanged(evt);
            }
        });
        add(jSpinY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 63, -1));

        jSpinX2.setName("jSpinX2"); // NOI18N
        jSpinX2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinX2StateChanged(evt);
            }
        });
        add(jSpinX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 63, -1));

        jSpinY2.setName("jSpinY2"); // NOI18N
        jSpinY2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinY2StateChanged(evt);
            }
        });
        add(jSpinY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 63, -1));

        jSpinX3.setName("jSpinX3"); // NOI18N
        jSpinX3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinX3StateChanged(evt);
            }
        });
        add(jSpinX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 63, -1));

        jSpinY3.setName("jSpinY3"); // NOI18N
        jSpinY3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinY3StateChanged(evt);
            }
        });
        add(jSpinY3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 63, -1));

        jSpinX4.setName("jSpinX4"); // NOI18N
        jSpinX4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinX4StateChanged(evt);
            }
        });
        add(jSpinX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 63, -1));

        jSpinY4.setName("jSpinY4"); // NOI18N
        jSpinY4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinY4StateChanged(evt);
            }
        });
        add(jSpinY4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 63, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinX1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinX1StateChanged
        effect.setX1((Integer) jSpinX1.getValue());
    }//GEN-LAST:event_jSpinX1StateChanged

    private void jSpinY1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinY1StateChanged
        effect.setY1((Integer) jSpinY1.getValue());
    }//GEN-LAST:event_jSpinY1StateChanged

    private void jSpinX2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinX2StateChanged
        effect.setX2((Integer) jSpinX2.getValue());
    }//GEN-LAST:event_jSpinX2StateChanged

    private void jSpinY2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinY2StateChanged
        effect.setY2((Integer) jSpinY2.getValue());
    }//GEN-LAST:event_jSpinY2StateChanged

    private void jSpinX3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinX3StateChanged
        effect.setX3((Integer) jSpinX3.getValue());
    }//GEN-LAST:event_jSpinX3StateChanged

    private void jSpinY3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinY3StateChanged
        effect.setY3((Integer) jSpinY3.getValue());
    }//GEN-LAST:event_jSpinY3StateChanged

    private void jSpinX4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinX4StateChanged
        effect.setX4((Integer) jSpinX4.getValue());
    }//GEN-LAST:event_jSpinX4StateChanged

    private void jSpinY4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinY4StateChanged
        effect.setY4((Integer) jSpinY4.getValue());
    }//GEN-LAST:event_jSpinY4StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinX1;
    private javax.swing.JSpinner jSpinX2;
    private javax.swing.JSpinner jSpinX3;
    private javax.swing.JSpinner jSpinX4;
    private javax.swing.JSpinner jSpinY1;
    private javax.swing.JSpinner jSpinY2;
    private javax.swing.JSpinner jSpinY3;
    private javax.swing.JSpinner jSpinY4;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

}
