/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MosaicControl.java
 *
 * Created on 2010-01-15, 01:51:51
 */

package webcamstudio.sources.effects.controls;

import webcamstudio.sources.effects.Perspective;

/**
 *
 * @author pballeux
 */
public class PerspectiveControl_Old extends javax.swing.JPanel {

    Perspective effect = null;
    /** Creates new form MosaicControl
     * @param effect */
    public PerspectiveControl_Old(Perspective effect) {
        initComponents();
        this.effect=effect;
        txtX1.setText((int)effect.getX1()+"");
        txtY1.setText((int)effect.getY1()+"");
        txtX2.setText((int)effect.getX2()+"");
        txtY2.setText((int)effect.getY2()+"");
        txtX3.setText((int)effect.getX3()+"");
        txtY3.setText((int)effect.getY3()+"");
        txtX4.setText((int)effect.getX4()+"");
        txtY4.setText((int)effect.getY4()+"");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JFormattedTextField();
        txtX2 = new javax.swing.JFormattedTextField();
        txtX3 = new javax.swing.JFormattedTextField();
        txtX4 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtY1 = new javax.swing.JFormattedTextField();
        txtY2 = new javax.swing.JFormattedTextField();
        txtY3 = new javax.swing.JFormattedTextField();
        txtY4 = new javax.swing.JFormattedTextField();

        label.setText("X1");
        label.setName("label"); // NOI18N

        jLabel1.setText("X2");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("X3");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("X4");
        jLabel3.setName("jLabel3"); // NOI18N

        txtX1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtX1.setText("0");
        txtX1.setName("txtX1"); // NOI18N
        txtX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1ActionPerformed(evt);
            }
        });
        txtX1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtX1FocusLost(evt);
            }
        });

        txtX2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtX2.setText("0");
        txtX2.setName("txtX2"); // NOI18N
        txtX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX2ActionPerformed(evt);
            }
        });
        txtX2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtX2FocusLost(evt);
            }
        });

        txtX3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtX3.setText("0");
        txtX3.setName("txtX3"); // NOI18N
        txtX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX3ActionPerformed(evt);
            }
        });
        txtX3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtX3FocusLost(evt);
            }
        });

        txtX4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtX4.setText("0");
        txtX4.setName("txtX4"); // NOI18N
        txtX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX4ActionPerformed(evt);
            }
        });
        txtX4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtX4FocusLost(evt);
            }
        });

        jLabel4.setText("Y1");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Y2");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText("Y3");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText("Y4");
        jLabel7.setName("jLabel7"); // NOI18N

        txtY1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtY1.setText("0");
        txtY1.setName("txtY1"); // NOI18N
        txtY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY1ActionPerformed(evt);
            }
        });
        txtY1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtY1FocusLost(evt);
            }
        });

        txtY2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtY2.setText("0");
        txtY2.setName("txtY2"); // NOI18N
        txtY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY2ActionPerformed(evt);
            }
        });
        txtY2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtY2FocusLost(evt);
            }
        });

        txtY3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtY3.setText("0");
        txtY3.setName("txtY3"); // NOI18N
        txtY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY3ActionPerformed(evt);
            }
        });
        txtY3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtY3FocusLost(evt);
            }
        });

        txtY4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtY4.setText("0");
        txtY4.setName("txtY4"); // NOI18N
        txtY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtY4ActionPerformed(evt);
            }
        });
        txtY4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtY4FocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtY4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1ActionPerformed
        effect.setX1(new Integer(txtX1.getText()));
    }//GEN-LAST:event_txtX1ActionPerformed

    private void txtX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX2ActionPerformed
        effect.setX2(new Integer(txtX2.getText()));
    }//GEN-LAST:event_txtX2ActionPerformed

    private void txtX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX3ActionPerformed
        effect.setX3(new Integer(txtX3.getText()));
    }//GEN-LAST:event_txtX3ActionPerformed

    private void txtX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX4ActionPerformed
        effect.setX4(new Integer(txtX4.getText()));
    }//GEN-LAST:event_txtX4ActionPerformed

    private void txtY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY1ActionPerformed
        effect.setY1(new Integer(txtY1.getText()));
    }//GEN-LAST:event_txtY1ActionPerformed

    private void txtY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY2ActionPerformed
        effect.setY2(new Integer(txtY2.getText()));
    }//GEN-LAST:event_txtY2ActionPerformed

    private void txtY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY3ActionPerformed
        effect.setY3(new Integer(txtY3.getText()));
    }//GEN-LAST:event_txtY3ActionPerformed

    private void txtY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtY4ActionPerformed
        effect.setY4(new Integer(txtY4.getText()));
    }//GEN-LAST:event_txtY4ActionPerformed

    private void txtX1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtX1FocusLost
        effect.setX1(new Integer(txtX1.getText()));
    }//GEN-LAST:event_txtX1FocusLost

    private void txtY1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtY1FocusLost
        effect.setY1(new Integer(txtY1.getText()));
    }//GEN-LAST:event_txtY1FocusLost

    private void txtX2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtX2FocusLost
        effect.setX2(new Integer(txtX2.getText()));
    }//GEN-LAST:event_txtX2FocusLost

    private void txtY2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtY2FocusLost
        effect.setY2(new Integer(txtY2.getText()));
    }//GEN-LAST:event_txtY2FocusLost

    private void txtX3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtX3FocusLost
        effect.setX3(new Integer(txtX3.getText()));
    }//GEN-LAST:event_txtX3FocusLost

    private void txtY3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtY3FocusLost
        effect.setY3(new Integer(txtY3.getText()));
    }//GEN-LAST:event_txtY3FocusLost

    private void txtX4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtX4FocusLost
        effect.setX4(new Integer(txtX4.getText()));
    }//GEN-LAST:event_txtX4FocusLost

    private void txtY4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtY4FocusLost
        effect.setY4(new Integer(txtY4.getText()));
    }//GEN-LAST:event_txtY4FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label;
    private javax.swing.JFormattedTextField txtX1;
    private javax.swing.JFormattedTextField txtX2;
    private javax.swing.JFormattedTextField txtX3;
    private javax.swing.JFormattedTextField txtX4;
    private javax.swing.JFormattedTextField txtY1;
    private javax.swing.JFormattedTextField txtY2;
    private javax.swing.JFormattedTextField txtY3;
    private javax.swing.JFormattedTextField txtY4;
    // End of variables declaration//GEN-END:variables

}
