/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestMixer.java
 *
 * Created on 4-Mar-2012, 2:44:13 PM
 */
package webcamstudio;

import webcamstudio.components.Viewer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.swing.DefaultComboBoxModel;
import webcamstudio.exporter.vloopback.VideoDevice;
import webcamstudio.mixers.Frame;
import webcamstudio.mixers.MasterMixer;
import webcamstudio.mixers.SystemAudioPlayer;
import webcamstudio.streams.SinkFile;
import webcamstudio.streams.SourceWebcam;

/**
 *
 * @author patrick
 */
public class TestMixer extends javax.swing.JFrame {

    boolean stopMe = false;
    Viewer v = new Viewer();

    /** Creates new form TestMixer */
    public TestMixer() {
        initComponents();
        viewer.add(v, BorderLayout.CENTER);
        v.setBackground(Color.red);
        v.setOpaque(true);
        v.setPreferredSize(new Dimension(320, 240));
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        VideoDevice[] devices = VideoDevice.getOutputDevices();
        for (VideoDevice d : devices){
            model.addElement(d.getFile().getAbsolutePath());
        }
        cboWebcams.setModel(model);
        pack();
    }

    private void render() throws LineUnavailableException {
        SourceWebcam webcam = new SourceWebcam(new File(cboWebcams.getSelectedItem().toString()));
        webcam.setRate(15);
        SinkFile sink = new SinkFile(new File("test.ogv"));
        MasterMixer.start();
        sink.setWidth(MasterMixer.getWidth());
        sink.setHeight(MasterMixer.getHeight());
        sink.setRate(MasterMixer.getRate());
        webcam.read();
        webcam.setVolume(100);
        SystemAudioPlayer audio = new SystemAudioPlayer();
        audio.play();
        sink.read();
        while (!stopMe) {
            Frame frame = MasterMixer.getCurrentFrame();
            if (frame != null) {
                BufferedImage img = MasterMixer.getCurrentFrame().getImage();
                if (img != null) {
                    v.setImage(img);
                    viewer.repaint();
                }
            }
            try {
                Thread.sleep(1000 / 10);
            } catch (InterruptedException ex) {
                Logger.getLogger(TestMixer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        sink.stop();
        webcam.stop();
        audio.stop();
        MasterMixer.stop();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cboWebcams = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewer.setBackground(java.awt.Color.black);
        viewer.setName("viewer"); // NOI18N
        viewer.setLayout(new java.awt.BorderLayout());
        getContentPane().add(viewer, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N

        jButton1.setText("Start");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Stop");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        cboWebcams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboWebcams.setName("cboWebcams"); // NOI18N
        jPanel1.add(cboWebcams);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        stopMe = false;
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    render();
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(TestMixer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stopMe = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TestMixer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboWebcams;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel viewer;
    // End of variables declaration//GEN-END:variables
}
