/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlGSTEffects.java
 *
 * Created on 2010-01-12, 23:52:34
 */
package webcamstudio.controls;

import webcamstudio.components.SourceListener;
import webcamstudio.sources.VideoSource;

/**
 *
 * @author pballeux
 */
public class ControlGSTEffects extends javax.swing.JPanel implements Controls {

    VideoSource source = null;
    String label = "GSTEFFECT";
    private SourceListener listener=null;
    /** Creates new form ControlGSTEffects */
    public ControlGSTEffects(VideoSource source) {
        initComponents();
        this.source = source;
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio.Languages");
        label = bundle.getString("GST_EFFECTS");

        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel();
        model.addElement(bundle.getString("NONE"));
        model.addElement("agingtv");
        model.addElement("quarktv");
        model.addElement("vertigotv");
        model.addElement("revtv");
        model.addElement("shagadelictv");
        model.addElement("edgetv");
        model.addElement("dicetv");
        model.addElement("rippletv");
        model.addElement("streaktv");
        model.addElement("warptv");
        cboEffects.setModel(model);
        if (source.getEffect().length() > 0) {
            cboEffects.setSelectedItem(source.getEffect());
        } else {
            cboEffects.setSelectedItem(0);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboEffects = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        jLabel1.setText(bundle.getString("GST_EFFECTS")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cboEffects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEffects.setName("cboEffects"); // NOI18N
        cboEffects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEffectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboEffects, 0, 130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboEffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboEffectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEffectsActionPerformed
        if (cboEffects.getSelectedIndex() == 0) {
            source.setEffect("");
        } else {
            source.setEffect(cboEffects.getSelectedItem().toString());
        }        
    }//GEN-LAST:event_cboEffectsActionPerformed

    @Override
    public String getLabel() {
        return label;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboEffects;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void removeControl() {
        source=null;
    }

    @Override
    public void setListener(SourceListener l) {
        listener=l;
    }
}
