/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlText.java
 *
 * Created on 2010-01-12, 23:51:15
 */
package webcamstudio.controls;

import java.awt.GraphicsEnvironment;
import webcamstudio.components.ColorChooser;
import webcamstudio.components.SourceListener;
import webcamstudio.sources.VideoSourceText;

/**
 *
 * @author pballeux
 */
public class ControlText extends javax.swing.JPanel implements Controls {

    VideoSourceText source = null;
    String label = "Capture";
    private SourceListener listener=null;
    /** Creates new form ControlText */
    public ControlText(VideoSourceText source) {
        initComponents();
        this.source = source;
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio.Languages");
        label = bundle.getString("FORMAT");
        spinWidth.setValue(source.getCaptureWidth());
        spinHeight.setValue(source.getCaptureHeight());
        slideFramerate.setValue(source.getFrameRate());
        javax.swing.DefaultComboBoxModel modelFont = new javax.swing.DefaultComboBoxModel(GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames(this.getLocale()));
        cboFontName.setModel(modelFont);
        cboFontName.setSelectedItem(source.getFont());
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel();
        model.addElement(bundle.getString("NONE"));
        model.addElement(bundle.getString("DOWN"));
        model.addElement(bundle.getString("UP"));
        model.addElement(bundle.getString("RIGHT"));
        model.addElement(bundle.getString("LEFT"));
        cboDirection.setModel(model);
        cboDirection.setSelectedIndex(source.getScrollingMode());
        txtContent.setText(source.getCustomText());
        cboFontSize.setSelectedItem(source.getFontSize() + "");
        spinOpacity.setValue(new Integer((int)(source.getBackgroundOpacity()*100)));
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWidth = new javax.swing.JLabel();
        spinWidth = new javax.swing.JSpinner();
        lblHeight = new javax.swing.JLabel();
        spinHeight = new javax.swing.JSpinner();
        lblFramrate = new javax.swing.JLabel();
        slideFramerate = new javax.swing.JSlider();
        lblDirection = new javax.swing.JLabel();
        cboDirection = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        btnForeground = new javax.swing.JButton();
        btnBackground = new javax.swing.JButton();
        lblTextSize = new javax.swing.JLabel();
        cboFontSize = new javax.swing.JComboBox();
        lblFontName = new javax.swing.JLabel();
        cboFontName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        spinOpacity = new javax.swing.JSpinner();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        lblWidth.setText(bundle.getString("WIDTH")); // NOI18N
        lblWidth.setName("lblWidth"); // NOI18N

        spinWidth.setName("spinWidth"); // NOI18N
        spinWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinWidthStateChanged(evt);
            }
        });

        lblHeight.setText(bundle.getString("HEIGHT")); // NOI18N
        lblHeight.setName("lblHeight"); // NOI18N

        spinHeight.setName("spinHeight"); // NOI18N
        spinHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinHeightStateChanged(evt);
            }
        });

        lblFramrate.setText(bundle.getString("TEXTSPEED")); // NOI18N
        lblFramrate.setName("lblFramrate"); // NOI18N

        slideFramerate.setMajorTickSpacing(15);
        slideFramerate.setMaximum(30);
        slideFramerate.setMinorTickSpacing(5);
        slideFramerate.setPaintLabels(true);
        slideFramerate.setPaintTicks(true);
        slideFramerate.setName("slideFramerate"); // NOI18N
        slideFramerate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slideFramerateStateChanged(evt);
            }
        });

        lblDirection.setText(bundle.getString("DIRECTION")); // NOI18N
        lblDirection.setName("lblDirection"); // NOI18N

        cboDirection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDirection.setName("cboDirection"); // NOI18N
        cboDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDirectionActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtContent.setColumns(20);
        txtContent.setRows(5);
        txtContent.setName("txtContent"); // NOI18N
        txtContent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContentFocusLost(evt);
            }
        });
        txtContent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContentKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtContent);

        btnForeground.setText(bundle.getString("FOREGROUNDCOLOR")); // NOI18N
        btnForeground.setName("btnForeground"); // NOI18N
        btnForeground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForegroundActionPerformed(evt);
            }
        });

        btnBackground.setText(bundle.getString("BACKGROUNDCOLOR")); // NOI18N
        btnBackground.setName("btnBackground"); // NOI18N
        btnBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackgroundActionPerformed(evt);
            }
        });

        lblTextSize.setText(bundle.getString("FONTSIZE")); // NOI18N
        lblTextSize.setName("lblTextSize"); // NOI18N

        cboFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "36", "48", "72" }));
        cboFontSize.setName("cboFontSize"); // NOI18N
        cboFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFontSizeActionPerformed(evt);
            }
        });

        lblFontName.setText(bundle.getString("FONTNAME")); // NOI18N
        lblFontName.setName("lblFontName"); // NOI18N

        cboFontName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFontName.setName("cboFontName"); // NOI18N
        cboFontName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFontNameActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("OPACITY")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        spinOpacity.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        spinOpacity.setName("spinOpacity"); // NOI18N
        spinOpacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinOpacityStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblFramrate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slideFramerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblWidth)
                        .addGap(18, 18, 18)
                        .addComponent(spinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDirection)
                            .addComponent(lblTextSize, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFontName)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboFontName, 0, 131, Short.MAX_VALUE)
                    .addComponent(cboFontSize, javax.swing.GroupLayout.Alignment.TRAILING, 0, 131, Short.MAX_VALUE)
                    .addComponent(cboDirection, 0, 131, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnForeground, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(190, 190, 190))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWidth)
                    .addComponent(spinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeight)
                    .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextSize)
                    .addComponent(cboFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFramrate))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDirection)
                                    .addComponent(cboDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboFontName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFontName)))
                            .addComponent(slideFramerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(btnForeground)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackground)
                    .addComponent(jLabel1)
                    .addComponent(spinOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinWidthStateChanged
        source.setCaptureWidth((Integer) spinWidth.getValue());
    }//GEN-LAST:event_spinWidthStateChanged

    private void spinHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinHeightStateChanged
        source.setCaptureHeight((Integer) spinHeight.getValue());
}//GEN-LAST:event_spinHeightStateChanged

    private void slideFramerateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slideFramerateStateChanged
        source.setFrameRate(slideFramerate.getValue());
}//GEN-LAST:event_slideFramerateStateChanged

    private void cboDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDirectionActionPerformed
        source.setScrollingMode(cboDirection.getSelectedIndex());
    }//GEN-LAST:event_cboDirectionActionPerformed

    private void txtContentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContentKeyTyped
        source.updateText(txtContent.getText());

    }//GEN-LAST:event_txtContentKeyTyped

    private void txtContentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContentFocusLost
        source.updateText(txtContent.getText());
    }//GEN-LAST:event_txtContentFocusLost

    private void btnForegroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForegroundActionPerformed
        webcamstudio.components.ColorChooser c = new ColorChooser(null, true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
        if (c.getColor() != null) {
            source.setForeground(c.getColor());
        }
    }//GEN-LAST:event_btnForegroundActionPerformed

    private void btnBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackgroundActionPerformed
        webcamstudio.components.ColorChooser c = new ColorChooser(null, true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
        if (c.getColor() != null) {
            source.setBackground(c.getColor());
        }

    }//GEN-LAST:event_btnBackgroundActionPerformed

    private void cboFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFontSizeActionPerformed
        source.setFontSize(new Integer(cboFontSize.getSelectedItem().toString()));
    }//GEN-LAST:event_cboFontSizeActionPerformed

    private void cboFontNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFontNameActionPerformed
        source.setFont(cboFontName.getSelectedItem().toString());
    }//GEN-LAST:event_cboFontNameActionPerformed

    private void spinOpacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinOpacityStateChanged
        source.setBackgroundOpacity(((Integer)spinOpacity.getValue()).floatValue()/100f);

    }//GEN-LAST:event_spinOpacityStateChanged

    @Override
    public String getLabel() {
        return label;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackground;
    private javax.swing.JButton btnForeground;
    private javax.swing.JComboBox cboDirection;
    private javax.swing.JComboBox cboFontName;
    private javax.swing.JComboBox cboFontSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDirection;
    private javax.swing.JLabel lblFontName;
    private javax.swing.JLabel lblFramrate;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblTextSize;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JSlider slideFramerate;
    private javax.swing.JSpinner spinHeight;
    private javax.swing.JSpinner spinOpacity;
    private javax.swing.JSpinner spinWidth;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables

    @Override
    public void removeControl() {
        source=null;
    }

    @Override
    public void setListener(SourceListener l) {
        listener=l;
    }
}
