/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourceControlDesktop.java
 *
 * Created on 23-Apr-2012, 10:16:29 AM
 */
package webcamstudio.components;

import webcamstudio.streams.SourceDesktop;

/**
 *
 * @author patrick
 */
public class SourceControlDesktop extends javax.swing.JPanel {

    SourceDesktop source = null;
    /** Creates new form SourceControlDesktop */
    public SourceControlDesktop(SourceDesktop source) {
        initComponents();
        this.source=source;
        chkFollowMouse.setSelected(source.isFollowingMouse());
        setName("Desktop");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkFollowMouse = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        chkFollowMouse.setText(bundle.getString("FOLLOW_MOUSE")); // NOI18N
        chkFollowMouse.setName("chkFollowMouse"); // NOI18N
        chkFollowMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFollowMouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chkFollowMouse)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chkFollowMouse)
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkFollowMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFollowMouseActionPerformed
        source.setFollowMouse(chkFollowMouse.isSelected());
    }//GEN-LAST:event_chkFollowMouseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkFollowMouse;
    // End of variables declaration//GEN-END:variables
}
