/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AudioMixerPanel.java
 *
 * Created on 2011-01-08, 13:34:01
 */

package webcamstudio.components;

import javax.swing.DefaultComboBoxModel;
import webcamstudio.layout.Layout;
import webcamstudio.sound.AudioMixer;

/**
 *
 * @author patrick
 */
public class AudioMixerPanel extends javax.swing.JPanel {
    
    Layout layout = null;
    AudioMixer audioMixer = null;
    /** Creates new form AudioMixerPanel */
    public AudioMixerPanel(Layout l,AudioMixer mixer) {
        initComponents();
        layout = l;
        audioMixer=mixer;
        sliderVolume.setValue(layout.getMicVolume());
        sliderLow.setValue(layout.getMicLow());
        sliderMiddle.setValue(layout.getMicMiddle());
        sliderHigh.setValue(layout.getMicHigh());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sliderVolume = new javax.swing.JSlider();
        sliderLow = new javax.swing.JSlider();
        sliderMiddle = new javax.swing.JSlider();
        sliderHigh = new javax.swing.JSlider();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        jLabel1.setText(bundle.getString("MICROPHONE")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("VOLUME")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("LOW_FILTER")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(bundle.getString("MIDDLE_FILTER")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(bundle.getString("HIGH_FILTER")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        sliderVolume.setPaintLabels(true);
        sliderVolume.setPaintTicks(true);
        sliderVolume.setName("sliderVolume"); // NOI18N
        sliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVolumeStateChanged(evt);
            }
        });

        sliderLow.setMaximum(12);
        sliderLow.setMinimum(-24);
        sliderLow.setPaintLabels(true);
        sliderLow.setPaintTicks(true);
        sliderLow.setValue(0);
        sliderLow.setName("sliderLow"); // NOI18N
        sliderLow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderLowStateChanged(evt);
            }
        });

        sliderMiddle.setMaximum(12);
        sliderMiddle.setMinimum(-24);
        sliderMiddle.setPaintLabels(true);
        sliderMiddle.setPaintTicks(true);
        sliderMiddle.setValue(0);
        sliderMiddle.setName("sliderMiddle"); // NOI18N
        sliderMiddle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMiddleStateChanged(evt);
            }
        });

        sliderHigh.setMaximum(12);
        sliderHigh.setMinimum(-24);
        sliderHigh.setPaintLabels(true);
        sliderHigh.setPaintTicks(true);
        sliderHigh.setValue(0);
        sliderHigh.setName("sliderHigh"); // NOI18N
        sliderHigh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderHighStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderLow, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(sliderVolume, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(sliderMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(sliderHigh, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sliderLow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sliderHigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sliderVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVolumeStateChanged
        layout.setMicVolume(sliderVolume.getValue());
        if (layout.isActive()){
            audioMixer.setVolume(sliderVolume.getValue());
        }
    }//GEN-LAST:event_sliderVolumeStateChanged

    private void sliderLowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderLowStateChanged
        layout.setMicLow(sliderLow.getValue());
        if (layout.isActive()){
            audioMixer.setLowFilter(sliderLow.getValue());
        }
    }//GEN-LAST:event_sliderLowStateChanged

    private void sliderMiddleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMiddleStateChanged
        layout.setMicMiddle(sliderMiddle.getValue());
        if (layout.isActive()){
            audioMixer.setMiddleFilter(sliderMiddle.getValue());
        }
    }//GEN-LAST:event_sliderMiddleStateChanged

    private void sliderHighStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderHighStateChanged
       layout.setMicHigh(sliderHigh.getValue());
        if (layout.isActive()){
            audioMixer.setHighFilter(sliderHigh.getValue());
        }
    }//GEN-LAST:event_sliderHighStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider sliderHigh;
    private javax.swing.JSlider sliderLow;
    private javax.swing.JSlider sliderMiddle;
    private javax.swing.JSlider sliderVolume;
    // End of variables declaration//GEN-END:variables

}
