/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChannelPanel.java
 *
 * Created on 23-Apr-2012, 12:17:31 AM
 */
package webcamstudio.components;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import webcamstudio.WebcamStudio;
import webcamstudio.channels.MasterChannels;
import webcamstudio.mixers.SystemPlayer;
import webcamstudio.streams.SourceChannel;
import webcamstudio.streams.Stream;
import webcamstudio.studio.Studio;
import webcamstudio.util.Tools;




/**
 *
 * @author patrick (modified by karl)
 */
public class ChannelPanel extends javax.swing.JPanel implements WebcamStudio.Listener, Studio.Listener {

    MasterChannels master = MasterChannels.getInstance();
    private DefaultListModel model = new DefaultListModel();
    private DefaultComboBoxModel aModel = new DefaultComboBoxModel();
    private ArrayList<String> CHCurrNext = new ArrayList<>();
    private ArrayList<Integer> CHTimers = new ArrayList<>();
    private ArrayList<String> ListChannels = new ArrayList<>();
    ArrayList<Stream> streamS = MasterChannels.getInstance().getStreams();
    String selectChannel=null;   
    int CHon =0;
    String CHNxName = null;
    int CHNextTime =0;
    int CHTimer = 0;
    private Timer CHt=new Timer();
    String CHptS= null;
    private Boolean StopCHpt=false;
    boolean inTimer=false;

    @Override
    public void resetAutoPLBtnState(ActionEvent evt) {
        btnAutoPlayList.setEnabled(true);
    }
    public interface Listener {
        public void resetBtnStates(java.awt.event.ActionEvent evt);    
    }
    static Listener listenerCP = null;
    public static void setListenerCP(Listener l) {
        listenerCP = l;
    }
    
    /**
     * Creates new form ChannelPanel
     */
    @SuppressWarnings("unchecked") 
    public ChannelPanel() {
        initComponents();
        final ChannelPanel instanceChPnl = this;
        lstChannels.setModel(model);
        lstNextChannel.setModel(aModel);
        WebcamStudio.setListener(instanceChPnl);
        Studio.setListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstChannelsScroll = new javax.swing.JScrollPane();
        lstChannels = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lstNextChannel = new javax.swing.JComboBox();
        ChDuration = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StopCHTimer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CHProgressTime = new javax.swing.JProgressBar();
        btnStopAllStream = new javax.swing.JButton();
        btnRenameCh = new javax.swing.JButton();
        btnAutoPlayList = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(238, 499));

        lstChannelsScroll.setName("lstChannelsScroll"); // NOI18N

        lstChannels.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstChannels.setName("lstChannels"); // NOI18N
        lstChannels.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstChannelsValueChanged(evt);
            }
        });
        lstChannelsScroll.setViewportView(lstChannels);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        jLabel1.setText(bundle.getString("Name")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtName.setName("txtName"); // NOI18N

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/list-add.png"))); // NOI18N
        btnAdd.setToolTipText(bundle.getString("ADD_CHANNEL")); // NOI18N
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/process-stop.png"))); // NOI18N
        btnRemove.setToolTipText(bundle.getString("REMOVE_CHANNEL")); // NOI18N
        btnRemove.setEnabled(false);
        btnRemove.setName("btnRemove"); // NOI18N
        btnRemove.setPreferredSize(new java.awt.Dimension(32, 30));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/media-playback-start.png"))); // NOI18N
        btnSelect.setToolTipText(bundle.getString("APPLY_CHANNEL")); // NOI18N
        btnSelect.setEnabled(false);
        btnSelect.setMinimumSize(new java.awt.Dimension(32, 30));
        btnSelect.setName("btnSelect"); // NOI18N
        btnSelect.setPreferredSize(new java.awt.Dimension(32, 30));
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/view-refresh.png"))); // NOI18N
        btnUpdate.setToolTipText(bundle.getString("UPDATE_CHANNEL")); // NOI18N
        btnUpdate.setEnabled(false);
        btnUpdate.setMinimumSize(new java.awt.Dimension(32, 25));
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.setPreferredSize(new java.awt.Dimension(32, 30));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lstNextChannel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lstNextChannel.setName("lstNextChannel"); // NOI18N
        lstNextChannel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstNextChannelActionPerformed(evt);
            }
        });

        ChDuration.setToolTipText("0 = Infinite");
        ChDuration.setName("ChDuration"); // NOI18N
        ChDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ChDurationStateChanged(evt);
            }
        });

        jLabel2.setText(bundle.getString("NEXT_CHANNEL")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("DURATION")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        StopCHTimer.setText(bundle.getString("STOP_CHANNEL_TIMER")); // NOI18N
        StopCHTimer.setEnabled(false);
        StopCHTimer.setName("StopCHTimer"); // NOI18N
        StopCHTimer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        StopCHTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopCHTimerActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(bundle.getString("CURRENT_CHANNEL_TIMER")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        CHProgressTime.setName("CHProgressTime"); // NOI18N

        btnStopAllStream.setText(bundle.getString("STOP_ALL")); // NOI18N
        btnStopAllStream.setName("btnStopAllStream"); // NOI18N
        btnStopAllStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopAllStreamActionPerformed(evt);
            }
        });

        btnRenameCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/edit.png"))); // NOI18N
        btnRenameCh.setToolTipText(bundle.getString("RENAME_CHANNEL")); // NOI18N
        btnRenameCh.setEnabled(false);
        btnRenameCh.setName("btnRenameCh"); // NOI18N
        btnRenameCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameChActionPerformed(evt);
            }
        });

        btnAutoPlayList.setText("Automatic Play-List");
        btnAutoPlayList.setToolTipText("Do an Automatic PlayList. Works Only with \"Load Media Folder\".");
        btnAutoPlayList.setEnabled(false);
        btnAutoPlayList.setName("btnAutoPlayList"); // NOI18N
        btnAutoPlayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoPlayListActionPerformed(evt);
            }
        });

        btnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/go-up.png"))); // NOI18N
        btnUp.setToolTipText("Move Channel UP");
        btnUp.setEnabled(false);
        btnUp.setName("btnUp"); // NOI18N
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/go-down.png"))); // NOI18N
        btnDown.setToolTipText("Move Channel DOWN");
        btnDown.setEnabled(false);
        btnDown.setName("btnDown"); // NOI18N
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopCHTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(txtName)
                        .addGap(1, 1, 1)
                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnRenameCh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstChannelsScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChDuration)
                            .addComponent(lstNextChannel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(CHProgressTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnStopAllStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutoPlayList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRenameCh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstChannelsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAutoPlayList, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lstNextChannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ChDuration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CHProgressTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStopAllStream, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StopCHTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        btnStopAllStream.getAccessibleContext().setAccessibleParent(StopCHTimer);
    }// </editor-fold>//GEN-END:initComponents

    private void lstChannelsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstChannelsValueChanged
        if (lstChannels.getSelectedIndex() != -1) {
            selectChannel = lstChannels.getSelectedValue().toString();
            int SelectCHIndex = lstChannels.getSelectedIndex();
            lstNextChannel.setSelectedItem(CHCurrNext.get(SelectCHIndex));
            ChDuration.setValue(CHTimers.get(SelectCHIndex)/1000);
            btnRemove.setEnabled(!inTimer);
            btnUp.setEnabled(!inTimer);
            btnDown.setEnabled(!inTimer);
            btnSelect.setEnabled(!inTimer);
            btnRenameCh.setEnabled(!inTimer);
            btnAdd.setEnabled(!inTimer);
            StopCHTimer.setEnabled(inTimer);
            btnUpdate.setEnabled(true);
            } else {
                btnRemove.setEnabled(false);
                btnSelect.setEnabled(false);
                btnUpdate.setEnabled(false);
        }
    }//GEN-LAST:event_lstChannelsValueChanged
    @SuppressWarnings("unchecked") 
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = txtName.getText();
        boolean noDuplicateCh = true;
        for (String chName : ListChannels){
            if (name.equals(chName)){
                noDuplicateCh = false;
                break;
            }
        }
        
        if (name.length() > 0 && noDuplicateCh) {
            master.addChannel(name);
            model.addElement(name);
            aModel.addElement(name);
            CHCurrNext.add(name);
            CHTimers.add(CHTimer);
            ListChannels.add(name);
            lstChannels.revalidate();
            lstNextChannel.revalidate();
        } else {
            if (!noDuplicateCh){
                ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, "Channel "+name+" Duplicated !!!");
                ResourceMonitor.getInstance().addMessage(label);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String name = lstChannels.getSelectedValue().toString();
        int SelectCHIndex = lstChannels.getSelectedIndex();
        master.removeChannel(name);
        model.removeElement(name);
        aModel.removeElement(name);
        CHCurrNext.remove(name);
        CHTimers.remove(SelectCHIndex);
        ListChannels.remove(name);
        lstChannels.revalidate();
        lstNextChannel.revalidate();
        btnRenameCh.setEnabled(false);
        btnUp.setEnabled(false);
        btnDown.setEnabled(false);
        btnRemove.setEnabled(false);
        StopCHTimer.setEnabled(inTimer);
    }//GEN-LAST:event_btnRemoveActionPerformed

    @Override
    public ArrayList<String> getCHCurrNext () {
        return CHCurrNext;
    }
    @Override
    public ArrayList<Integer> getCHTimers () {
        return CHTimers;
    }   
    
    @Override
    public void removeChannels(String removeSc, int a) {
        model.removeElement(removeSc);
        aModel.removeElement(removeSc);
        CHCurrNext.remove(removeSc);
        CHTimers.remove(a);
        ListChannels.remove(removeSc);
    }   
    @SuppressWarnings("unchecked") 
    @Override
    public void addLoadingChannel(String name) {
        if (name.length() > 0) {
            model.addElement(name);
            aModel.addElement(name);
            ListChannels.add(name);
            lstChannels.revalidate();
       }
    }   
    @Override
    public void stopChTime(java.awt.event.ActionEvent evt) {
        RemoteStopCHTimerActionPerformed(evt);
    }
    
    @Override
    public void resetBtnStates(java.awt.event.ActionEvent evt) {
        btnRenameCh.setEnabled(false);
        btnUp.setEnabled(false);
        btnDown.setEnabled(false);
        btnRemove.setEnabled(false);
        btnSelect.setEnabled(false);
        txtName.setText("");
        CHCurrNext.clear();
        CHTimers.clear();
        StopCHTimer.setEnabled(false);
        ChDuration.setValue(0);
    }

    class UpdateCHtUITask extends TimerTask {
        @Override
        public void run() {
            CHptS=null;
//            int CHpt=0;
            int CHpTemptime = CHNextTime/1000;
            CHProgressTime.setValue(0);
            CHProgressTime.setStringPainted(true);
            CHProgressTime.setMaximum(CHpTemptime);             
            while (CHpTemptime>0 && StopCHpt==false){
                CHptS = Integer.toString(CHpTemptime);
                CHProgressTime.setValue(CHpTemptime);
                CHProgressTime.setString(CHptS);
                Tools.sleep(1000);
                CHpTemptime -= 1;
            }
            UpdateCHtUITask.this.stop();
        }
        public void stop() {
            StopCHpt=true;
        }
   }
    
   class TSelectActionPerformed extends TimerTask {
        @Override
        public void run(){
            CHon = lstChannels.getSelectedIndex();
            CHNxName = CHCurrNext.get(CHon);
            int n =0;
            for (String h : ListChannels) {
                 if (h.equals(CHNxName)) {
                    CHNextTime = CHTimers.get(n);
                 }
                 n += 1;
            }
            lstChannels.setSelectedValue(CHNxName, true);
            String name = lstChannels.getSelectedValue().toString();
            System.out.println("Apply Select: "+name);
            Tools.sleep(50);
            master.selectChannel(CHNxName);
            if (CHNextTime != 0) {
                CHt=new Timer();
                CHt.schedule(new TSelectActionPerformed(),CHNextTime);
                CHNextTime = CHTimers.get(lstChannels.getSelectedIndex());
                StopCHpt=false;
                CHProgressTime.setValue(0);
                CHt.schedule(new UpdateCHtUITask(),0);
            } else {
                CHt.cancel();
                CHt.purge();
                StopCHpt=true;
                lstChannels.setEnabled(true);
                ChDuration.setEnabled(true);
                btnStopAllStream.setEnabled(true);
                btnSelect.setEnabled(true);
                btnRenameCh.setEnabled(true);
                btnUp.setEnabled(true);
                btnDown.setEnabled(true);
                btnRemove.setEnabled(true);
                btnAdd.setEnabled(true);
                inTimer=false;
                CHProgressTime.setValue(0);
                CHProgressTime.setString("0");
                StopCHTimer.setEnabled(inTimer);                
            }
	}        
    }    
    
    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        String name = lstChannels.getSelectedValue().toString();
        System.out.println("Apply Select: "+name);
        master.selectChannel(name);
        if (CHTimers.get(lstChannels.getSelectedIndex()) != 0) {
            inTimer=true;
            btnRenameCh.setEnabled(false);
            btnUp.setEnabled(false);
            btnDown.setEnabled(false);
            btnRemove.setEnabled(false);
            btnAdd.setEnabled(false);
            lstChannels.setEnabled(false);
            ChDuration.setEnabled(false);
            StopCHTimer.setEnabled(inTimer);
            btnStopAllStream.setEnabled(false);
            btnSelect.setEnabled(false);
            CHt=new Timer();
            CHt.schedule(new TSelectActionPerformed(),CHTimers.get(lstChannels.getSelectedIndex()));
            CHNextTime = CHTimers.get(lstChannels.getSelectedIndex());
            StopCHpt=false;
            CHt.schedule(new UpdateCHtUITask(),0);
        }
    }//GEN-LAST:event_btnSelectActionPerformed
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String name = lstChannels.getSelectedValue().toString();
        master.updateChannel(name);
        ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, "Channel "+name+" Updated");
        ResourceMonitor.getInstance().addMessage(label);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lstNextChannelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstNextChannelActionPerformed
        if (lstChannels.getSelectedIndex() != -1) {
           String nextChannel = lstNextChannel.getSelectedItem().toString();
           int ChIndex = lstChannels.getSelectedIndex();
           CHCurrNext.set(ChIndex, nextChannel);
           } 
    }//GEN-LAST:event_lstNextChannelActionPerformed

    private void ChDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ChDurationStateChanged
        CHTimer = ChDuration.getValue().hashCode()* 1000;
        if (lstChannels.getSelectedIndex() != -1) {
            int ChIndex = lstChannels.getSelectedIndex();
            CHTimers.set(ChIndex, CHTimer);
        }
    }//GEN-LAST:event_ChDurationStateChanged
    private void RemoteStopCHTimerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CHt.cancel();
        CHt.purge();
        StopCHpt=true;
        lstChannels.setEnabled(true);
        ChDuration.setEnabled(true);
        btnStopAllStream.setEnabled(true);
        btnSelect.setEnabled(true);
        btnRenameCh.setEnabled(true);
        btnUp.setEnabled(true);
        btnDown.setEnabled(true);
        btnRemove.setEnabled(true);
        btnAdd.setEnabled(true);
        inTimer=false;
        CHProgressTime.setValue(0);
        CHProgressTime.setString("0");
        StopCHTimer.setEnabled(inTimer);
    }                                           
    private void StopCHTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopCHTimerActionPerformed
        RemoteStopCHTimerActionPerformed(evt);
        ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, "Channel Timer Stopped.");
        ResourceMonitor.getInstance().addMessage(label);
    }//GEN-LAST:event_StopCHTimerActionPerformed

    private void btnStopAllStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopAllStreamActionPerformed
        SystemPlayer.getInstance(null).stop();
        Tools.sleep(30);
        MasterChannels.getInstance().stopAllStream();
        for (Stream s : streamS){
            s.updateStatus();
        }
        Tools.sleep(30);
        listenerCP.resetBtnStates(evt);
        ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, "All Stopped.");
        ResourceMonitor.getInstance().addMessage(label);
        System.gc();
    }//GEN-LAST:event_btnStopAllStreamActionPerformed
    @SuppressWarnings("unchecked")
    private void btnRenameChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameChActionPerformed
        if (lstChannels != null) {
            if (txtName.getText().length() > 0) {
                String rnName = txtName.getText();
                String chName = lstChannels.getSelectedValue().toString();
                int selectCHIndex = lstChannels.getSelectedIndex();
                for (Stream stream : streamS){
                    for (SourceChannel sc : stream.getChannels()) {
                        if (sc.getName().equals(chName)){
                            sc.setName(rnName);
                        }
                    }
                }
                int coun =  0;
                for (String chCurNx : CHCurrNext){
                    if (chCurNx.equals(chName)){
                        CHCurrNext.set(coun, rnName);
                    }
                    coun++;
                }
                lstNextChannel.revalidate();
                master.addChannelAt(rnName, selectCHIndex);
                master.removeChannelAt(chName);
                model.removeElement(chName);
                aModel.removeElement(chName);
                CHTimers.remove(selectCHIndex);
                ListChannels.remove(chName);
                lstChannels.revalidate();
                model.insertElementAt(rnName, selectCHIndex);
                aModel.insertElementAt(rnName, selectCHIndex);
                CHTimers.add(selectCHIndex, CHTimer);
                ListChannels.add(selectCHIndex, rnName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();
                btnRenameCh.setEnabled(false);
                btnUp.setEnabled(false);
                btnDown.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnRenameChActionPerformed
    @SuppressWarnings("unchecked")
    private void btnAutoPlayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoPlayListActionPerformed
        ArrayList<Stream> allStreams = MasterChannels.getInstance().getStreams();
        for (Stream s : allStreams) {
            String sourceName = s.getName();
            System.out.println("Source: "+sourceName);
            String shortName = "";
            if (sourceName.length() > 30) {
                shortName = s.getName().substring(0, 30)+" ...";
            } else {
                shortName = sourceName;
            }
            if (shortName.length() > 0) {
                s.setIsPlaying(true);
                master.addChannel(shortName);
                model.addElement(shortName);
                aModel.addElement(shortName);
                CHCurrNext.add(shortName);
                CHTimers.add(CHTimer);
                ListChannels.add(shortName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();
                s.setIsPlaying(false);
            }
        }
        int index = 0;
        int lastItemIndex = ListChannels.size()-1;
//        System.out.println("LastItemIndex: " + lastItemIndex);
        for (Stream s : allStreams) {
            if (!"N/A".equals(s.getStreamTime())) {
                String sPrepTime = s.getStreamTime().replaceAll("s", "");
                int sDuration = Integer.parseInt(sPrepTime);
                CHTimer = sDuration * 1000;
                CHTimers.set(index, CHTimer);
            } else {
                CHTimers.set(index, 0);
            }
            if (index < lastItemIndex) {
                String nextChannel = ListChannels.get(index+1);
                CHCurrNext.set(index, nextChannel);
            } else {
                String nextChannel = ListChannels.get(0);
                CHCurrNext.set(index, nextChannel);
            }
//            System.out.println("Name: "+s.getName()+" Duration: "+CHTimer);
            index++;
        }
        btnAutoPlayList.setEnabled(false);
    }//GEN-LAST:event_btnAutoPlayListActionPerformed
    @SuppressWarnings("unchecked")
    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        int selectedCHIndex = lstChannels.getSelectedIndex();
        String selectedChName = ListChannels.get(selectedCHIndex);
        int selectedCHTimer = CHTimers.get(selectedCHIndex);
        int nextCHIndex;
        String nextChName;
        int nextCHTimer;
//        System.out.println("List Next Channels: "+CHCurrNext);
//        System.out.println("List Channels Timers: "+CHTimers);
        if (lstChannels != null && selectedCHIndex < ListChannels.size() - 1) {
            if (selectedCHIndex == ListChannels.size() - 2) {
                nextCHIndex = selectedCHIndex + 1;
                nextChName = ListChannels.get(nextCHIndex);
                nextCHTimer = CHTimers.get(nextCHIndex);
//                System.out.println("Master Channels Before:"+master.getChannels());
                // Update Master Channels
                master.removeChannelAt(selectedChName);
                master.removeChannelAt(nextChName);
                master.addToChannels(nextChName);
                master.addToChannels(selectedChName);
                // Update Streams Channels
                for (Stream stream : streamS){
                    String streamName =stream.getClass().getName();
                    if (streamName.contains("Sink")){
                    } else {
                        SourceChannel tempSelSC = null;
                        SourceChannel tempNextSC = null;
                        for (SourceChannel sc : stream.getChannels()) {
                            if (sc.getName().equals(selectedChName)){
                                tempSelSC = sc;
                            }
                            if (sc.getName().equals(nextChName)){
                                tempNextSC = sc;
                            }
                        }                   
                        stream.addChannelAt(tempSelSC, nextCHIndex);
                        stream.addChannelAt(tempNextSC, selectedCHIndex);
                    }
                }
//                System.out.println("Master Channels After:"+master.getChannels());
                // Update UI lists and WS lists Channels
                model.removeElement(selectedChName);
                model.removeElement(nextChName);                
                aModel.removeElement(selectedChName);
                aModel.removeElement(nextChName);
                CHCurrNext.remove(selectedChName);
                CHTimers.remove(selectedCHIndex);
                CHTimers.remove(selectedCHIndex);
                ListChannels.remove(selectedChName);
                ListChannels.remove(nextChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();
//                System.out.println("List Next Channels Remove: "+CHCurrNext);
                model.addElement(nextChName);
                model.addElement(selectedChName);
                aModel.addElement(nextChName);
                aModel.addElement(selectedChName);
                CHCurrNext.add(selectedCHIndex, selectedChName);
                CHTimers.add(nextCHTimer);
                CHTimers.add(selectedCHTimer);
                ListChannels.add(nextChName);
                ListChannels.add(selectedChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();      
                lstChannels.setSelectedIndex(nextCHIndex);
//                System.out.println("List Next Channels Insert: "+CHCurrNext);
            } else {
                nextCHIndex = selectedCHIndex + 1;
                nextChName = ListChannels.get(nextCHIndex);
                nextCHTimer = CHTimers.get(nextCHIndex);
//                System.out.println("Master Channels Before:"+master.getChannels());
                // Update Master Channels
                master.removeChannelAt(selectedChName);
                master.removeChannelAt(nextChName);
                master.addChannelAt(nextChName, selectedCHIndex);
                master.addChannelAt(selectedChName, nextCHIndex);
                // Update Streams Channels
                for (Stream stream : streamS){
                    String streamName =stream.getClass().getName();
                    if (streamName.contains("Sink")){
                    } else {
                        SourceChannel tempSelSC = null;
                        SourceChannel tempNextSC = null;
                        for (SourceChannel sc : stream.getChannels()) {
                            if (sc.getName().equals(selectedChName)){
                                tempSelSC = sc;
                            }
                            if (sc.getName().equals(nextChName)){
                                tempNextSC = sc;
                            }
                        }                   
                        stream.addChannelAt(tempSelSC, nextCHIndex);
                        stream.addChannelAt(tempNextSC, selectedCHIndex);
                    }
                }
//                System.out.println("Master Channels After:"+master.getChannels());
                // Update UI Channels lists and WS lists
                model.removeElement(selectedChName);
                model.removeElement(nextChName);                
                aModel.removeElement(selectedChName);
                aModel.removeElement(nextChName);
                if (selectedCHIndex == 0) {
                  CHCurrNext.remove(selectedChName);
                  CHCurrNext.remove(nextChName);
                } else {
                    CHCurrNext.remove(selectedChName);
                }
                CHTimers.remove(selectedCHIndex);
                CHTimers.remove(selectedCHIndex);
//                System.out.println("List Channels Timers Removed: "+CHTimers);
                ListChannels.remove(selectedChName);
                ListChannels.remove(nextChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();
//                System.out.println("List Next Channels Remove: "+CHCurrNext);
                model.insertElementAt(nextChName, selectedCHIndex);
                model.insertElementAt(selectedChName, nextCHIndex);
                aModel.insertElementAt(nextChName, selectedCHIndex);
                aModel.insertElementAt(selectedChName, nextCHIndex);
                if (selectedCHIndex == 0) {
                    CHCurrNext.add(selectedCHIndex, selectedChName);
                    CHCurrNext.add(nextChName);
                } else {
                    CHCurrNext.add(selectedCHIndex, selectedChName);
                }
                CHTimers.add(selectedCHIndex, nextCHTimer);
                CHTimers.add(nextCHIndex, selectedCHTimer);
//                System.out.println("List Channels Timers After: "+CHTimers);
                ListChannels.add(selectedCHIndex, nextChName);
                ListChannels.add(nextCHIndex, selectedChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();      
                lstChannels.setSelectedIndex(nextCHIndex);
//                System.out.println("List Next Channels Insert: "+CHCurrNext);
            }
        }
    }//GEN-LAST:event_btnDownActionPerformed
    @SuppressWarnings("unchecked")
    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        int selectedCHIndex = lstChannels.getSelectedIndex();
        String selectedChName = ListChannels.get(selectedCHIndex);
        int selectedCHTimer = CHTimers.get(selectedCHIndex);
        int previousCHIndex;
        String previousChName;
        int previousCHTimer;
        int previous2CHIndex;
//        System.out.println("List Next Channels: "+CHCurrNext);
//        System.out.println("List Channels Timers: "+CHTimers);
        if (lstChannels != null && selectedCHIndex > 0) {
            if (selectedCHIndex == 1) {
                previousCHIndex = selectedCHIndex - 1;
                previousChName = ListChannels.get(previousCHIndex);
                previousCHTimer = CHTimers.get(previousCHIndex);
//                System.out.println("Master Channels Before:"+master.getChannels());
                // Update Master Channels
                master.removeChannelAt(selectedChName);
                master.removeChannelAt(previousChName);
                master.addChannelAt(selectedChName, previousCHIndex);
                master.addChannelAt(previousChName, selectedCHIndex);
                // Update Streams Channels
                for (Stream stream : streamS){
                    String streamName =stream.getClass().getName();
                    if (streamName.contains("Sink")){
                    } else {
                        SourceChannel tempSelSC = null;
                        SourceChannel tempPrevSC = null;
                        for (SourceChannel sc : stream.getChannels()) {
                            if (sc.getName().equals(selectedChName)){
                                tempSelSC = sc;
                            }
                            if (sc.getName().equals(previousChName)){
                                tempPrevSC = sc;
                            }
                        }                   
                        stream.addChannelAt(tempSelSC, previousCHIndex);
                        stream.addChannelAt(tempPrevSC, selectedCHIndex);
                    }
                }
//                System.out.println("Master Channels After:"+master.getChannels());
                // Update UI lists and WS lists Channels
                model.removeElement(selectedChName);
                model.removeElement(previousChName);                
                aModel.removeElement(selectedChName);
                aModel.removeElement(previousChName);
                CHCurrNext.remove(selectedChName);
                CHTimers.remove(selectedCHIndex);
                CHTimers.remove(previousCHIndex);
                ListChannels.remove(selectedChName);
                ListChannels.remove(previousChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();               
//                System.out.println("List Next Channels Remove: "+CHCurrNext);                
                model.insertElementAt(selectedChName, previousCHIndex);
                model.insertElementAt(previousChName, selectedCHIndex);
                aModel.insertElementAt(selectedChName, previousCHIndex);
                aModel.insertElementAt(previousChName, selectedCHIndex);
                CHCurrNext.add(previousCHIndex, previousChName);
                CHTimers.add(previousCHIndex, selectedCHTimer);
                CHTimers.add(selectedCHIndex, previousCHTimer);                
                ListChannels.add(previousCHIndex, selectedChName);
                ListChannels.add(selectedCHIndex, previousChName);                
                lstChannels.revalidate();
                lstNextChannel.revalidate();                     
                CHCurrNext.remove(ListChannels.size()-1);
                lstNextChannel.revalidate();
                CHCurrNext.add(ListChannels.size()-1, selectedChName);
                lstNextChannel.revalidate();               
                lstChannels.setSelectedIndex(previousCHIndex);               
//                System.out.println("List Next Channels Insert: "+CHCurrNext);
            } else {
                previous2CHIndex = selectedCHIndex - 2;
                previousCHIndex = selectedCHIndex - 1;
                previousChName = ListChannels.get(previousCHIndex);
                previousCHTimer = CHTimers.get(previousCHIndex);
//                System.out.println("Master Channels Before:"+master.getChannels());
                // Update Master Channels
                master.removeChannelAt(selectedChName);
                master.removeChannelAt(previousChName);
                master.addChannelAt(selectedChName, previousCHIndex);
                master.addChannelAt(previousChName, selectedCHIndex);
                // Update Streams Channels
                for (Stream stream : streamS){
                    String streamName =stream.getClass().getName();
                    if (streamName.contains("Sink")){
                    } else {
                        SourceChannel tempSelSC = null;
                        SourceChannel tempPrevSC = null;
                        for (SourceChannel sc : stream.getChannels()) {
                            if (sc.getName().equals(selectedChName)){
                                tempSelSC = sc;
                            }
                            if (sc.getName().equals(previousChName)){
                                tempPrevSC = sc;
                            }
                        }                   
                        stream.addChannelAt(tempSelSC, previousCHIndex);
                        stream.addChannelAt(tempPrevSC, selectedCHIndex);
                    }
                }
//                System.out.println("Master Channels After:"+master.getChannels());
                // Update UI Channels lists and WS lists
                model.removeElement(selectedChName);
                model.removeElement(previousChName);                
                aModel.removeElement(selectedChName);
                aModel.removeElement(previousChName);
                CHCurrNext.remove(selectedChName);
                CHTimers.remove(selectedCHIndex);
                CHTimers.remove(previousCHIndex);
                ListChannels.remove(selectedChName);
                ListChannels.remove(previousChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();
//                System.out.println("List Next Channels Remove: "+CHCurrNext);
                model.insertElementAt(selectedChName, previousCHIndex);
                model.insertElementAt(previousChName, selectedCHIndex);
                aModel.insertElementAt(selectedChName, previousCHIndex);
                aModel.insertElementAt(previousChName, selectedCHIndex);
                CHCurrNext.add(previousCHIndex, previousChName);
                CHTimers.add(previousCHIndex, selectedCHTimer);
                CHTimers.add(selectedCHIndex, previousCHTimer);                
                ListChannels.add(previousCHIndex, selectedChName);
                ListChannels.add(selectedCHIndex, previousChName);
                lstChannels.revalidate();
                lstNextChannel.revalidate();      
                lstChannels.setSelectedIndex(previousCHIndex);
//                System.out.println("List Next Channels Insert: "+CHCurrNext);
                CHCurrNext.remove(previous2CHIndex);
                lstNextChannel.revalidate();
                CHCurrNext.add(previous2CHIndex, selectedChName);
                lstNextChannel.revalidate();
            }
        }
    }//GEN-LAST:event_btnUpActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar CHProgressTime;
    private javax.swing.JSpinner ChDuration;
    private javax.swing.JButton StopCHTimer;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAutoPlayList;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRenameCh;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnStopAllStream;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList lstChannels;
    private javax.swing.JScrollPane lstChannelsScroll;
    private javax.swing.JComboBox lstNextChannel;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
    
}
