/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PulseAudioInputSelecter.java
 *
 * Created on 2011-05-22, 19:57:34
 */
package webcamstudio.components;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import webcamstudio.layout.Layout;

/**
 *
 * @author patrick
 */
public class PulseAudioInputSelecter extends javax.swing.JPanel {

    PulseAudioManager p = new PulseAudioManager();
    Layout layout = null;

    /** Creates new form PulseAudioInputSelecter */
    public PulseAudioInputSelecter(Layout l) {
        initComponents();
        layout = l;
        try {
            p.update();
        } catch (IOException ex) {
            Logger.getLogger(PulseAudioInputSelecter.class.getName()).log(Level.SEVERE, null, ex);
        }
        javax.swing.DefaultComboBoxModel sourceModel = new DefaultComboBoxModel(p.getSources());
        javax.swing.DefaultComboBoxModel appsModel = new DefaultComboBoxModel(p.getApps());
        cboSources.setModel(sourceModel);
        cboApps.setModel(appsModel);
        cboSources.setSelectedItem(l.getAudioSource());
        cboApps.getEditor().setItem(l.getAudioApp());
        if (cboSources.getModel().getSize() > 0 && layout.getAudioSource().length()==0) {
            cboSources.setSelectedIndex(0);
            layout.setAudioSource(cboSources.getSelectedItem().toString());

        }
        if (cboApps.getModel().getSize() > 0 && layout.getAudioApp().length()==0) {
            cboApps.setSelectedIndex(0);
            layout.setAudioApp(cboApps.getSelectedItem().toString());
        }
        if (cboSources.getSelectedItem() != null) {
            cboSources.setToolTipText(cboSources.getSelectedItem().toString());
        }
        if (cboApps.getSelectedItem() != null) {
            cboApps.setToolTipText(cboApps.getSelectedItem().toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboSources = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboApps = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        jLabel1.setText(bundle.getString("PULSEAUDIO_SOURCE")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cboSources.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSources.setName("cboSources"); // NOI18N
        cboSources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSourcesActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("PULSEAUDIO_APP_RECODER")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cboApps.setEditable(true);
        cboApps.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboApps.setName("cboApps"); // NOI18N
        cboApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAppsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSources, 0, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboApps, 0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboSources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboApps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboSourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSourcesActionPerformed
        cboSources.setToolTipText(cboSources.getSelectedItem().toString());
        if (cboSources.getModel().getSize() > 0) {
            layout.setAudioSource(cboSources.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cboSourcesActionPerformed

    private void cboAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAppsActionPerformed
        cboApps.setToolTipText(cboApps.getSelectedItem().toString());
        if (cboApps.getModel().getSize() > 0) {
            layout.setAudioApp(cboApps.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cboAppsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboApps;
    private javax.swing.JComboBox cboSources;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
