/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResourceMonitor.java
 *
 * Created on 15-Apr-2012, 1:04:46 AM
 */
package webcamstudio.components;

import java.util.Timer;
import java.util.TimerTask;
import webcamstudio.mixers.MasterFrameBuilder;
import webcamstudio.mixers.MasterMixer;

/**
 *
 * @author patrick
 */
public class ResourceMonitor extends javax.swing.JPanel {

    Timer timer = new Timer();
    private static String message = "";
    private static long messageMark = 0;
    /** Creates new form ResourceMonitor */
    public ResourceMonitor() {
        initComponents();
        timer.scheduleAtFixedRate(new ResourceMonitorThread(this), 0, 1000);
    }
    public static void setMessage(String m){
        message=m;
        messageMark = System.currentTimeMillis();
    }
    public void updateInfo(){
        long maxMem = Runtime.getRuntime().maxMemory() / 1024 / 1024;
        long usedMem = ((Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory()) / 1024 / 1024);
        memLevel.setMaximum((int)maxMem);
        memLevel.setValue((int)usedMem);
        memLevel.setString(usedMem + "MB/" + maxMem + "MB");
        lblFPS.setText(MasterMixer.getInstance().getFPS() + " fps");
        lblMixerSize.setText(MasterMixer.getInstance().getWidth()+ "X" + MasterMixer.getInstance().getHeight());
        lblMessage.setText(message);
        if (System.currentTimeMillis()-messageMark > 5000){
            message = "";
            messageMark=System.currentTimeMillis();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memLevel = new javax.swing.JProgressBar();
        lblFPS = new javax.swing.JLabel();
        lblMixerSize = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        memLevel.setName("memLevel"); // NOI18N
        memLevel.setStringPainted(true);

        lblFPS.setText("jLabel1");
        lblFPS.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblFPS.setName("lblFPS"); // NOI18N

        lblMixerSize.setText("jLabel1");
        lblMixerSize.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblMixerSize.setName("lblMixerSize"); // NOI18N

        lblMessage.setText("jLabel1");
        lblMessage.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblMessage.setName("lblMessage"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFPS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMixerSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFPS)
                        .addComponent(lblMixerSize)
                        .addComponent(lblMessage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFPS;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMixerSize;
    private javax.swing.JProgressBar memLevel;
    // End of variables declaration//GEN-END:variables
}
class ResourceMonitorThread extends TimerTask{
    ResourceMonitor monitor;
    public ResourceMonitorThread(ResourceMonitor m){
        monitor=m;
    }
    @Override
    public void run() {
        monitor.updateInfo();
    }
}