/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourceControlTransitions.java
 *
 * Created on 23-Apr-2012, 11:28:40 AM
 */
package webcamstudio.components;

import webcamstudio.streams.SourceChannel;
import webcamstudio.streams.Stream;

/**
 *
 * @author patrick
 */
public class SourceControlChannels extends javax.swing.JPanel {
    Stream source = null;
    /** Creates new form SourceControlTransitions
     * @param source */
    @SuppressWarnings("unchecked") 
    public SourceControlChannels(Stream source) {
        initComponents();
        this.source=source;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnApplyAllCh = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        setName(bundle.getString("CHANNELS_CTRL")); // NOI18N
        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        btnApplyAllCh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webcamstudio/resources/tango/chan-app.png"))); // NOI18N
        btnApplyAllCh.setText("Apply in All Channels");
        btnApplyAllCh.setToolTipText("Apply Current Stream State/Settings in All Channels.");
        btnApplyAllCh.setName("btnApplyAllCh"); // NOI18N
        btnApplyAllCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyAllChActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnApplyAllCh, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnApplyAllCh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyAllChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyAllChActionPerformed
        SourceChannel sch = null;
        for (int i=0; i < source.getChannels().size(); i++){
            String scName = source.getChannels().get(i).getName();
            sch=SourceChannel.getChannel(scName, source);
            source.removeChannelAt(i);
            source.addChannelAt(sch,i);
        }
        ResourceMonitorLabel label = new ResourceMonitorLabel(System.currentTimeMillis()+10000, source.getName() + " Settings Applied to all Channels.");
        ResourceMonitor.getInstance().addMessage(label);
    }//GEN-LAST:event_btnApplyAllChActionPerformed
    @SuppressWarnings("deprecation")     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyAllCh;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
