/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlShapes.java
 *
 * Created on 2010-01-12, 23:53:15
 */
package webcamstudio.controls;

import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import webcamstudio.components.Shapes;
import webcamstudio.components.SourceListener;
import webcamstudio.sources.VideoSource;

/**
 *
 * @author pballeux
 */
public class ControlShapes extends javax.swing.JPanel implements Controls {

    private VideoSource source = null;
    private String label = "Shapes";
    Shapes shapes = new Shapes();
    private SourceListener listener=null;
    /** Creates new form ControlShapes */
    public ControlShapes(VideoSource source) {
        initComponents();
        this.source = source;
        javax.swing.DefaultComboBoxModel model = new javax.swing.DefaultComboBoxModel(shapes.getKeys());
        model.insertElementAt("Custom", 0);
        model.insertElementAt("None", 0);
        cboShapes.setModel(model);
        cboShapes.revalidate();

        javax.swing.DefaultListCellRenderer renderer = new javax.swing.DefaultListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean hasFocus) {
                Component comp = super.getListCellRendererComponent(list, value, index, isSelected, hasFocus);
                JLabel label = (JLabel) comp;
                if (shapes.getImage(value.toString()) != null || index == 1) {
                    BufferedImage img = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
                    Image shape = shapes.getImage(value.toString());
                    if (index == 1) {
                        shape = shapes.getImage("custom");
                    }
                    if (shape != null) {
                        img.createGraphics().drawImage(shape, 0, 0, 16, 16, 0, 0, shape.getWidth(null), shape.getHeight(null), null);
                        label.setIcon(new ImageIcon(img));
                    }
                }

                return comp;
            }
        };
        cboShapes.setRenderer(renderer);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio.Languages");
        label = bundle.getString("SHAPES");
        lblCurrentCustomShape.setText(source.getCustomShapeFileName() + " ");
        if (source.getShapeName().equals("None") || source.getShapeName().length() == 0) {
            cboShapes.setSelectedIndex(0);
        } else if (source.getShapeName().equals("custom")) {
            cboShapes.setSelectedIndex(1);
        } else {
            cboShapes.setSelectedItem(source.getShapeName());
        }
        chkReverseShape.setSelected(source.isReverseShapeMask());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShapes = new javax.swing.JLabel();
        cboShapes = new javax.swing.JComboBox();
        lblCustomShape = new javax.swing.JLabel();
        lblCurrentCustomShape = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        chkReverseShape = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        lblShapes.setText(bundle.getString("SHAPES")); // NOI18N
        lblShapes.setName("lblShapes"); // NOI18N

        cboShapes.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        cboShapes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboShapes.setName("cboShapes"); // NOI18N
        cboShapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboShapesActionPerformed(evt);
            }
        });

        lblCustomShape.setText(bundle.getString("CUSTOMSHAPE")); // NOI18N
        lblCustomShape.setName("lblCustomShape"); // NOI18N

        lblCurrentCustomShape.setText("  ");
        lblCurrentCustomShape.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCurrentCustomShape.setName("lblCurrentCustomShape"); // NOI18N

        btnBrowse.setText(bundle.getString("BROWSE")); // NOI18N
        btnBrowse.setName("btnBrowse"); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        chkReverseShape.setText(bundle.getString("REVERSESHAPE")); // NOI18N
        chkReverseShape.setName("chkReverseShape"); // NOI18N
        chkReverseShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReverseShapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblShapes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboShapes, 0, 338, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomShape)
                            .addComponent(lblCurrentCustomShape, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkReverseShape)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblShapes)
                    .addComponent(cboShapes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomShape)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentCustomShape)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkReverseShape)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboShapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboShapesActionPerformed
        switch (cboShapes.getSelectedIndex()) {
            case 0:
                source.setShape(null);
                source.setShapeName("");
                break;
            case 1:
                source.setShape(shapes.getImage("custom"));
                source.setShapeName("custom");
                break;
            default:
                source.setShape(shapes.getImage(cboShapes.getSelectedItem().toString()));
                source.setShapeName(cboShapes.getSelectedItem().toString());
                break;
        }

    }//GEN-LAST:event_cboShapesActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser(source.getCustomShapeFileName());
        chooser.setAcceptAllFileFilterUsed(false);
        javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter("PNG", "png");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        chooser.showOpenDialog(this);
        if (chooser.getSelectedFile() != null) {
            try {
                BufferedImage img = javax.imageio.ImageIO.read(chooser.getSelectedFile());
                shapes.setCustom(img);
                source.setCustomShapeFileName(chooser.getSelectedFile().getAbsolutePath());
                source.setShape(img);
                source.setShapeName("custom");
                lblCurrentCustomShape.setText(source.getCustomShapeFileName());
                cboShapes.setSelectedIndex(1);
                cboShapes.revalidate();

            } catch (IOException ex) {
                Logger.getLogger(ControlShapes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void chkReverseShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReverseShapeActionPerformed
        source.doReverseShapeMask(chkReverseShape.isSelected());
    }//GEN-LAST:event_chkReverseShapeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JComboBox cboShapes;
    private javax.swing.JCheckBox chkReverseShape;
    private javax.swing.JLabel lblCurrentCustomShape;
    private javax.swing.JLabel lblCustomShape;
    private javax.swing.JLabel lblShapes;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getLabel() {
        return label;
    }

    @Override
    public void removeControl() {
        source = null;
    }

    @Override
    public void setListener(SourceListener l) {
        listener=l;
    }
}
