/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlIRC.java
 *
 * Created on 2010-01-12, 23:51:30
 */
package webcamstudio.controls;

import java.awt.GraphicsEnvironment;
import webcamstudio.components.ColorChooser;
import webcamstudio.components.SourceListener;
import webcamstudio.sources.VideoSourceIRC;
import webcamstudio.sources.VideoSourceIRCListener;

/**
 *
 * @author pballeux
 */
public class ControlIRC extends javax.swing.JPanel implements Controls, VideoSourceIRCListener {

    VideoSourceIRC source = null;
    String label = "IRC";
    private SourceListener listener=null;
    /** Creates new form ControlIRC */
    public ControlIRC(VideoSourceIRC source) {
        initComponents();
        this.source = source;
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio.Languages");
        label = bundle.getString("IRC");
        spinWidth.setValue(source.getCaptureWidth());
        spinHeight.setValue(source.getCaptureHeight());
        javax.swing.DefaultComboBoxModel modelFont = new javax.swing.DefaultComboBoxModel(GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames(this.getLocale()));
        cboFontName.setModel(modelFont);
        cboFontName.setSelectedItem(source.getFont());
        txtContent.setText(source.getCustomText());
        cboFontSize.setSelectedItem(source.getFontSize() + "");
        source.addIRCListener(this);
        String[] values = source.getLocation().split(":");
        String host = values[0];
        String port = values[1];
        String room = values[2];
        txtServer.setText(host);
        txtPort.setText(port);
        txtChatRoom.setText(room);
        txtNickName.setText(source.getNick());
        spinOpacity.setValue(new Integer((int)(source.getBackgroundOpacity()*100)));

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWidth = new javax.swing.JLabel();
        spinWidth = new javax.swing.JSpinner();
        lblHeight = new javax.swing.JLabel();
        spinHeight = new javax.swing.JSpinner();
        btnForeground = new javax.swing.JButton();
        btnBackground = new javax.swing.JButton();
        cboFontSize = new javax.swing.JComboBox();
        lblFontName = new javax.swing.JLabel();
        cboFontName = new javax.swing.JComboBox();
        lblTextSize = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtChatRoom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNickName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPort = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        spinOpacity = new javax.swing.JSpinner();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        lblWidth.setText(bundle.getString("WIDTH")); // NOI18N
        lblWidth.setName("lblWidth"); // NOI18N

        spinWidth.setName("spinWidth"); // NOI18N
        spinWidth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinWidthStateChanged(evt);
            }
        });

        lblHeight.setText(bundle.getString("HEIGHT")); // NOI18N
        lblHeight.setName("lblHeight"); // NOI18N

        spinHeight.setName("spinHeight"); // NOI18N
        spinHeight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinHeightStateChanged(evt);
            }
        });

        btnForeground.setText(bundle.getString("FOREGROUNDCOLOR")); // NOI18N
        btnForeground.setName("btnForeground"); // NOI18N
        btnForeground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForegroundActionPerformed(evt);
            }
        });

        btnBackground.setText(bundle.getString("BACKGROUNDCOLOR")); // NOI18N
        btnBackground.setName("btnBackground"); // NOI18N
        btnBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackgroundActionPerformed(evt);
            }
        });

        cboFontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "36", "48", "72" }));
        cboFontSize.setName("cboFontSize"); // NOI18N
        cboFontSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFontSizeActionPerformed(evt);
            }
        });

        lblFontName.setText(bundle.getString("FONTNAME")); // NOI18N
        lblFontName.setName("lblFontName"); // NOI18N

        cboFontName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFontName.setName("cboFontName"); // NOI18N
        cboFontName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFontNameActionPerformed(evt);
            }
        });

        lblTextSize.setText(bundle.getString("FONTSIZE")); // NOI18N
        lblTextSize.setName("lblTextSize"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtContent.setColumns(20);
        txtContent.setEditable(false);
        txtContent.setLineWrap(true);
        txtContent.setRows(5);
        txtContent.setWrapStyleWord(true);
        txtContent.setName("txtContent"); // NOI18N
        jScrollPane1.setViewportView(txtContent);

        jLabel1.setText(bundle.getString("IRC_SERVER")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        txtServer.setName("txtServer"); // NOI18N
        txtServer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtServerFocusLost(evt);
            }
        });

        jLabel2.setText(bundle.getString("CHAT_ROOM")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        txtChatRoom.setName("txtChatRoom"); // NOI18N
        txtChatRoom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChatRoomFocusLost(evt);
            }
        });

        jLabel3.setText(bundle.getString("NICK_NAME")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        txtNickName.setName("txtNickName"); // NOI18N
        txtNickName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNickNameFocusLost(evt);
            }
        });

        jLabel4.setText(bundle.getString("PORT")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        txtPort.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtPort.setName("txtPort"); // NOI18N
        txtPort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPortFocusLost(evt);
            }
        });

        jLabel5.setText(bundle.getString("OPACITY")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        spinOpacity.setName("spinOpacity"); // NOI18N
        spinOpacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinOpacityStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWidth)
                        .addGap(18, 18, 18)
                        .addComponent(spinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnForeground)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBackground)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinOpacity, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFontName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFontName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPort, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChatRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNickName, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWidth)
                    .addComponent(spinWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeight)
                    .addComponent(spinHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForeground)
                    .addComponent(btnBackground)
                    .addComponent(jLabel5)
                    .addComponent(spinOpacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextSize)
                    .addComponent(cboFontName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFontName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChatRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spinWidthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinWidthStateChanged
        source.setCaptureWidth((Integer) spinWidth.getValue());
}//GEN-LAST:event_spinWidthStateChanged

    private void spinHeightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinHeightStateChanged
        source.setCaptureHeight((Integer) spinHeight.getValue());
}//GEN-LAST:event_spinHeightStateChanged

    private void btnForegroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForegroundActionPerformed
        webcamstudio.components.ColorChooser c = new ColorChooser(null, true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
        if (c.getColor() != null) {
            source.setForeground(c.getColor());
        }
    }//GEN-LAST:event_btnForegroundActionPerformed

    private void btnBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackgroundActionPerformed
        webcamstudio.components.ColorChooser c = new ColorChooser(null, true);
        c.setLocationRelativeTo(this);
        c.setVisible(true);
        if (c.getColor() != null) {
            source.setBackground(c.getColor());
        }
}//GEN-LAST:event_btnBackgroundActionPerformed

    private void cboFontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFontSizeActionPerformed
        source.setFontSize(new Integer(cboFontSize.getSelectedItem().toString()));
}//GEN-LAST:event_cboFontSizeActionPerformed

    private void cboFontNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFontNameActionPerformed
        source.setFont(cboFontName.getSelectedItem().toString());
}//GEN-LAST:event_cboFontNameActionPerformed

    private void txtServerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtServerFocusLost
        source.setChatroom(txtServer.getText(), txtPort.getText(), txtChatRoom.getText(), txtNickName.getText());
    }//GEN-LAST:event_txtServerFocusLost

    private void txtPortFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPortFocusLost
        source.setChatroom(txtServer.getText(), txtPort.getText(), txtChatRoom.getText(), txtNickName.getText());
    }//GEN-LAST:event_txtPortFocusLost

    private void txtChatRoomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChatRoomFocusLost
        source.setChatroom(txtServer.getText(), txtPort.getText(), txtChatRoom.getText(), txtNickName.getText());
    }//GEN-LAST:event_txtChatRoomFocusLost

    private void txtNickNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNickNameFocusLost
        source.setChatroom(txtServer.getText(), txtPort.getText(), txtChatRoom.getText(), txtNickName.getText());
    }//GEN-LAST:event_txtNickNameFocusLost

    private void spinOpacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinOpacityStateChanged
        source.setBackgroundOpacity(((Integer)spinOpacity.getValue()).floatValue()/100f);
    }//GEN-LAST:event_spinOpacityStateChanged

    @Override
    public String getLabel() {
        return label;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackground;
    private javax.swing.JButton btnForeground;
    private javax.swing.JComboBox cboFontName;
    private javax.swing.JComboBox cboFontSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFontName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblTextSize;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JSpinner spinHeight;
    private javax.swing.JSpinner spinOpacity;
    private javax.swing.JSpinner spinWidth;
    private javax.swing.JTextField txtChatRoom;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtNickName;
    private javax.swing.JFormattedTextField txtPort;
    private javax.swing.JTextField txtServer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void newLine(VideoSourceIRC irc, String from, String text) {
        txtContent.append(from + ": " + text + "\n");
    }

    @Override
    public void removeControl() {
        source.removeIRCListener(this);
        source=null;
    }

    @Override
    public void setListener(SourceListener l) {
        listener=l;
    }
}
