/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlLayoutSources.java
 *
 * Created on 16-Oct-2011, 2:38:07 PM
 */
package webcamstudio.controls;

import webcamstudio.components.LayoutManager2;
import javax.swing.DefaultComboBoxModel;
import webcamstudio.layout.Layout;
import webcamstudio.layout.LayoutItem;
import webcamstudio.sources.VideoSource;
import webcamstudio.sources.VideoSourceLayout;

/**
 *
 * @author patrick
 */
public class ControlLayoutSources extends javax.swing.JPanel {

    private Layout layout = null;
    private LayoutManager2 manager = null;

    /** Creates new form ControlLayoutSources */
    public ControlLayoutSources(Layout layout, LayoutManager2 manager) {
        initComponents();
        this.manager = manager;
        this.layout = layout;

        DefaultComboBoxModel model = new DefaultComboBoxModel(Layout.getLayouts().values().toArray());
        
        for (Layout l : Layout.getLayouts().values()) {
            removeCircularSources(l, model);
        }
        cboLayouts.setModel(model);
    }

    private boolean removeCircularSources(Layout currentLayout, DefaultComboBoxModel model) {
        boolean found = false;
        if (currentLayout == layout){
            found=true;
        }
        for (LayoutItem item : currentLayout.getItems()) {
            if (item.getSource() instanceof VideoSourceLayout) {
                Layout sourceLayout = Layout.getLayouts().get(item.getSource().getLocation());
                if (sourceLayout == layout) {
                    found=true;
                } else{
                    found |= removeCircularSources(sourceLayout, model);
                }
                
            }
            
        }
        if (found){
            model.removeElement(currentLayout);
        }
        return found;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboLayouts = new javax.swing.JComboBox();
        btnAddAsSource = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("webcamstudio/Languages"); // NOI18N
        jLabel1.setText(bundle.getString("LAYOUTS")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cboLayouts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLayouts.setName("cboLayouts"); // NOI18N

        btnAddAsSource.setText(bundle.getString("ADD_LAYOUT_AS_SOURCE")); // NOI18N
        btnAddAsSource.setName("btnAddAsSource"); // NOI18N
        btnAddAsSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAsSourceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboLayouts, 0, 310, Short.MAX_VALUE))
                    .addComponent(btnAddAsSource, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboLayouts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAsSource)
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAsSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAsSourceActionPerformed
        if (cboLayouts.getSelectedItem() != null) {
            Layout sourceLayout = (Layout) cboLayouts.getSelectedItem();
            VideoSourceLayout source = new VideoSourceLayout(sourceLayout.getUUID());
            layout.addSource(source);
            manager.updateLayoutItemList();
        }
    }//GEN-LAST:event_btnAddAsSourceActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAsSource;
    private javax.swing.JComboBox cboLayouts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
